-- phpMyAdmin SQL Dump
-- version 4.6.5.1
-- https://www.phpmyadmin.net/
--
-- Client :  localhost
-- Généré le :  Mer 05 Juillet 2017 à 21:20
-- Version du serveur :  5.5.55-0+deb8u1
-- Version de PHP :  7.0.19-1~dotdeb+8.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `commercial`
--

-- --------------------------------------------------------

--
-- Structure de la table `article`
--

CREATE TABLE `article` (
  `id` int(11) NOT NULL,
  `ref` varchar(250) NOT NULL,
  `name` varchar(500) NOT NULL,
  `smallDesc` varchar(500) NOT NULL,
  `about` varchar(2500) NOT NULL,
  `image` varchar(500) NOT NULL,
  `categorie` int(11) NOT NULL,
  `tags` varchar(500) NOT NULL,
  `prix` double NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Contenu de la table `article`
--

INSERT INTO `article` (`id`, `ref`, `name`, `smallDesc`, `about`, `image`, `categorie`, `tags`, `prix`) VALUES
(1, '', 'Article 1', 'smallDesc article 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 100),
(2, '', 'Article 2', 'smallDesc article 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 10),
(3, '', 'Article 3', 'smallDesc article 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 30),
(4, '', 'Article 4', 'smallDesc article 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 100),
(5, '', 'Article 5', 'smallDesc article 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 79),
(6, '', 'Article 6', 'smallDesc article 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 500),
(7, '', 'Article 7', 'smallDesc article 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 40),
(8, '', 'Article 8', 'smallDesc article 8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 85),
(9, '', 'Article 9', 'smallDesc article 9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 71),
(10, '', 'Article 10', 'smallDesc article 10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 97),
(11, '', 'Chose 1', 'smallDesc article 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempor, ex in ornare elementum, neque turpis laoreet neque, a tincidunt est leo pellentesque arcu. Vivamus sollicitudin arcu sit amet ligula sodales sagittis sit amet a velit. Praesent luctus faucibus nunc, tempor convallis arcu accumsan viverra. Aenean vel cursus sapien, ac blandit neque. Quisque in mi placerat, dapibus leo et, pretium nunc. Sed sagittis orci arcu, quis accumsan leo placerat ut. Suspendisse potenti. Sed pharetra mi augue. Aenean commodo risus non risus suscipit sodales. Nam id risus malesuada, rutrum mauris eget, maximus nunc. Pellentesque tincidunt accumsan quam, eu dictum enim aliquet in. Duis pellentesque lacus quis sem tempus ornare. Donec tempus massa vitae nunc lobortis viverra. Donec ut quam accumsan, iaculis velit sed, elementum quam.\\r\\n\\r\\nIn rhoncus sit amet sapien nec luctus. Aenean sit amet augue vitae urna pellentesque laoreet sed in enim. Maecenas lacus enim, condimentum porttitor libero sed, sagittis tempor lacus. Phasellus facilisis metus vitae nisl volutpat, rhoncus gravida ipsum viverra. Suspendisse massa quam, tincidunt nec risus eget, posuere maximus magna. Aliquam in erat non mi ultrices pharetra id in magna. Quisque purus leo, consectetur ut aliquet eget, lacinia ut eros. Curabitur vestibulum consectetur enim. Vestibulum tempor finibus est sed tempus. Cras venenatis massa nec elit ullamcorper, semper facilisis purus eleifend. Donec auctor sodales purus, id accumsan dolor finibus vitae.\\r\\n\\r\\nPraesent sollicitudin nisl turpis, ac dignissim nibh dapibus non. Nam ultricies nulla ut tortor lobortis, vel rutrum metus feugiat. Cras vitae lorem elit. In elementum gravida sapien. Phasellus at gravida dolor. In sollicitudin in sem id finibus. Mauris in cursus ex. Duis ac lacus vitae nisl sollicitudin vestibulum. Aliquam sodales facilisis ligula sit amet blandit. Pellentesque bibendum finibus massa ut gravida. Fusce ac ligula hendrerit, dictum elit ac, fringilla risus. Suspendisse imperdiet scelerisque magna, sit amet sagittis nunc. Nullam sagittis, quam in ultrices fermentum, orci sapien facilisis nunc, vel fringilla massa nibh eu magna. Integer lobortis sed nisi nec vulputate.\\r\\n\\r\\nCurabitur vitae nunc nulla. Donec sodales non lorem ac vestibulum. Vestibulum id placerat massa, sed auctor ipsum. Suspendisse potenti. Quisque diam dui, imperdiet eget est a, lobortis ornare quam. Vivamus non ex egestas, hendrerit nunc ac, placerat sem. Nullam at quam orci.\\r\\n\\r\\nPe', '', 1, 'test', 100);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `article`
--
ALTER TABLE `article`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `article`
--
ALTER TABLE `article`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
